### PR TITLE
IRI Content Update

### PR DESCRIPTION
**Pull request by EmbeddedAndroid**
This series aims to improve the layout and the content for the IRI node installation guide. Some notable changes include:

  * Added rationale about why a user may want to run their own node
  * Create submenu for Linux and Docker installation
  * For Linux installations, expand the details about running the prebuilt JAR or building from source. This also includes basic details about network setup, and configuration recommendations.
  * For Docker installations, created a new guide to either build the Docker image locally or run the prebuild from Dockerhub. This also includes network setup and configuration recommendations.
  * Add myself as a team member, and twitter handle.

As far as the Windows installation goes, it has been dropped in favor of Docker, as it's supported by the developers, and provides multi-platform support including Windows.

### CODE REVIEW

**Comment by EmbeddedAndroid** [comment]
@l3wi fyi, I don't have privilege to add you as a reviewer.

**Comment by l3wi** [comment]
Looks good.

I tried to sort out the weird menu. Will try to figure it out separately. Merging.

**Comment by NelsonPython** [comment]
Prebuilt IRI JAVA Archive option questions:

1. Should we add a note that "target" is the folder where the iri jar is located?

2. CHANGED: export IRI_JAR_PATH="$(pwd)/target/iri*.jar
TO: export IRI_JAR_PATH="$(pwd)/iri*.jar

3. In the prior draft we set JAVA_MIN_MEMORY=2GB
This instruction is no longer included. Do we need to set it?

4. Port Mapping
TCP default port is 15600 - right?

5. Checking Node Status
See screen shot

**Comment by EmbeddedAndroid** [comment]
Hey Nelson,

I have a few improvements to this guide I'm working on now, I'll include your suggestions in my next PR.

1) I'll add a note about the "target" folder where the built java archive is output.

2) Depends if you built from source or used the prebuilt, I'll make a note of it.

3) Yup, good catch, I'll add.

4) 14600 is the default TCP/UDP peering port (p2p network), I belive you want to use 14465 for the IRI API calls.

5) Hrrm not sure why you are not able to connect to 14265 on localhost.

**Comment by EmbeddedAndroid** [comment]
@NelsonPython see https://github.com/iotaledger/docs/pull/32

**Pull request merged**
